# Generated by Django 5.0.2 on 2025-04-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symptoms', models.CharField(max_length=1000)),
                ('prescription', models.CharField(max_length=1000)),
                ('vet', models.CharField(max_length=100)),
                ('downloads', models.FileField(blank=True, null=True, upload_to='pet_medical_record/')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date_of_injection', models.DateField()),
                ('brand', models.CharField(max_length=100)),
                ('next', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
