# Generated by Django 5.0.2 on 2025-04-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='pet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.identityinformation'),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='pet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.identityinformation'),
        ),
    ]
