# Generated by Django 5.0.2 on 2025-04-08 13:06

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_comment_created_at_alter_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='BankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_uuid', models.UUIDField(default=uuid.uuid4)),
                ('order_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('call_back_url', models.URLField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 16, 36, 9, 577913)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2025, 4, 10)),
        ),
    ]
