# Generated by Django 5.0.2 on 2025-05-06 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_bankcustomer_bankpayment_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankpayment',
            old_name='customer_uuid',
            new_name='trans_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 17, 21, 29, 453704)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2025, 5, 8)),
        ),
    ]
