# Generated by Django 5.0.2 on 2025-05-08 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_customer_uuid_bankpayment_trans_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpayment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 19, 11, 31, 973727)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2025, 5, 10)),
        ),
    ]
