# Generated by Django 5.0.2 on 2025-04-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
